### ISSUE TITLE
500 Error on API request

### ISSUE THREAD

**Issue by contaldi** [publichealthengland/coronavirus-dashboard-api-python-sdk#13]
Hello,

I have been using the API for daily downloads of the updated case counts for utla and ltla areas. This stopped working yesterday with a 500 error returned. If this is a timeout issue could you please allow longer queries? this was working last week and I have to produce a daily report. Many thanks, Carlo.

`FailedRequestError: 
Request failed .... 500 - Internal Server Error
Response .......... No response
URL ............... https://api.coronavirus.data.gov.uk/v1/data?filters=areaType%3Dutla&structure=%7B%22areaType%22%3A%22areaType%22%2C%22areaName%22%3A%22areaName%22%2C%22areaCode%22%3A%22areaCode%22%2C%22specimenDate%22%3A%22date%22%2C%22dailyLabConfirmedCases%22%3A%22newCasesBySpecimenDate%22%2C%22totalLabConfirmedCases%22%3A%22cumCasesBySpecimenDate%22%7D&format=json&page=30
Decoded URL ....... https://api.coronavirus.data.gov.uk/v1/data?filters=areaType=utla&structure={"areaType":"areaType","areaName":"areaName","areaCode":"areaCode","specimenDate":"date","dailyLabConfirmedCases":"newCasesBySpecimenDate","totalLabConfirmedCases":"cumCasesBySpecimenDate"}&format=json&page=30
Parameters:
{ 'filters': 'areaType=utla',
  'format': 'json',
  'page': 30,
  'structure': '{"areaType":"areaType","areaName":"areaName","areaCode":"areaCode","specimenDate":"date","dailyLabConfirmedCases":"newCasesBySpecimenDate","totalLabConfirmedCases":"cumCasesBySpecimenDate"}'}
`

**Comment by xenatisch** [comment]
Hi @contaldi 

Thank you for reporting this. 

I looked into the issue and identified the problem, which was being caused due to a minor bug caused by a last-minute update we pushed this afternoon.
 
I just fixed and pushed a new version of the API. The issue should now be rectified.
 
Please let me know if you have any difficulties.

**Comment by contaldi** [comment]
Thanks @xenatisch, I can confirm it is working from my end.
