### ISSUE TITLE
areaType

### ISSUE THREAD

**Issue by ryamoo** [publichealthengland/coronavirus-dashboard-api-python-sdk#2]
Can an example or method be provided for obtaining a list of supported "areaType"?

**Comment by xenatisch** [comment]
@ryamoo Thank you for getting in touch. 

This was an oversight on my side which has been rectified. You should now be able to see the `areaType` parameter values in [the documentations](https://coronavirus-staging.data.gov.uk/developers-guide#filters-authorised_filter_metrics), under **See a list of valid values for the areaType metric**.

**Comment by ryamoo** [comment]
@xenatisch That's great - thank you for a quick reply and for adding it so fast.
