### ISSUE TITLE
Retrieve historical data for ltla

### ISSUE THREAD

**Issue by bhavesh0009** [publichealthengland/coronavirus-dashboard-api-python-sdk#4]
Although in the example it is demonstrated that data can be retrieved for historical dates as well
```
england_only = [
    'areaType=nation',
    'areaName=England'
]
```
 However when we change filter of areaType to ltla, it only returns data for 4th august. Even adding a filter for a date does not provide output from the previous date.

```
ltla_filter = [
    'areaType=ltla',
    'areaName=Warwick'
]
cases_and_deaths = {
    "date":"date",
    "areaName":"areaName",
    "areaCode":"areaCode",
    "newCasesByPublishDate":"newCasesByPublishDate",
    "cumCasesByPublishDate":"cumCasesByPublishDate",
    "newDeathsByDeathDate":"newDeathsByDeathDate",
    "cumDeathsByDeathDate":"cumDeathsByDeathDate"
}
api = Cov19API(filters=ltla_filter, structure=cases_and_deaths)
data = api.get_json()  # Returns a dictionary
print(data)
```

`{'data': [{'date': '2020-08-04', 'areaName': 'Warwick', 'areaCode': 'E07000222', 'newCasesByPublishDate': None, 'cumCasesByPublishDate': 445, 'newDeathsByDeathDate': None, 'cumDeathsByDeathDate': 78}], 'lastUpdate': '2020-08-04T21:35:21.000000Z', 'length': 1, 'totalPages': 1}`

**Comment by xenatisch** [comment]
Hi @bhavesh0009 

Thank you for getting in touch. 

The issue you have raised is almost identical to #1 - could I possibly as you to have a look my (fairly comprehensive) response over there?

Let me know if you need additional help, and I will be more than happy to provide more details.

**Comment by ryamoo** [comment]
@bhavesh0009 what are you using to retrieve the data?
I used the paginated example python code within Power BI, and was successfully able to retrieve 50 pages of LTLA data. Your results might suggest you've added the "latestBy" in your query, which only returns the latest result.

**Comment by xenatisch** [comment]
Hi @ryamoo - The issue that @bhavesh0009 reported is related to the metrics. We don't have historical records for  `...CasesByPublishDate` in our database at `utla` or `ltla` levels - only the `...CasesBySpecimenDate`. 

Could I possibly make a request? We have had quite a few queries regarding PowerBI, and it is not really my domain. I also don't have a license for it and it would take a while for me to submit a request and get it approved. If you feel like it and the time, it would be a great contribution and help us and a lot of our users - including some local authorities - if you could please create a simple, brief tutorial on how to use PowerBI with our Python or R SDK to retrieve the data. It could be a word document, a YouTube video, an HTML page, anything you like. Get in touch with me via covid19-tech@phe.gov.uk if you have any questions or need more info.

**Comment by bhavesh0009** [comment]
@xenatisch are different metrics used for different nations? I am able to get England and Wales historical information with specimen date but not Scotland or NI data.

**Comment by xenatisch** [comment]
@bhavesh0009 That's because Scotland and NI don't currently provide their data by specimen date, although they might soon. Right now, you should be able to get the data for them by `...CasesByPublishDate`.

**Comment by bhavesh0009** [comment]
> @bhavesh0009 That's because Scotland and NI don't currently provide their data by specimen date, although they might soon. Right now, you should be able to get the data for them by `...CasesByPublishDate`.

Thanks @xenatisch for prompt reply. I agree that historical data is present at Nation level with structure of CasesByPublishDate. But same information is not present at LTLA level for Scotland.
