### ISSUE TITLE
Elixir SDK

### ISSUE THREAD

**Issue by CallumVass** [publichealthengland/coronavirus-dashboard-api-python-sdk#7]
Hiya,

I wasn't sure where to create this issue so have followed @jchannon's lead and created an issue here, apologize.

I have created an Elixir implementation of the SDK here, I'm happy to transfer ownership if you so wish.
I've tried to follow the same programming style as the JS and Python SDK's and have implemented the test's in the same way.

Here is a link to the repo if you wanted to check it out: https://github.com/CallumVass/coronavirus-dashboard-api-elixir-sdk

Thanks

**Comment by xenatisch** [comment]
Hi @CallumVass 

Thank you for your offer. We are very grateful. I have to admit, Elixir is one language I wasn't expecting! Nice surprise.

Of course, we would love to take ownership of the project. I have done some experiments on the language, but I'm certainly not an Elixir programmer... I could probably do the maintenance and add new features, but might have to rely on your support if something goes wrong. 

You could transfer the ownership to me as a proxy, and I will then transfer it onto PHE. 

Once again, on behalf of myself, our team, and PHE, thank you. :)

**Comment by CallumVass** [comment]
Hi @xenatisch 

That's fine, I'm more then happy to provide support where required and I'll transfer the code over to you now. :)

In terms of next steps, I'm not sure what CI you are using but you'd need to publish the package to Hex. Here is a link with more information if you need it: https://hex.pm/docs/publish . Most of the work has been done in the mix.exs file (https://hex.pm/docs/publish#example-mixexs-file), you should just need to add a description and package function

If you need any help just let me know, thanks

**Comment by xenatisch** [comment]
All done... once again, thank you for the contribution. 

Re the CI, we are using GitHub Actions. I'll create an account on Hex and set up the secrets. Will let you know once that's done.

I'll take care of the description. 

The only thing is that we need to add some docs to the code, but that'll mainly consist of copying and pasting the docs from the Python code given the fact that you have followed the exact same pattern. 

Thanks Callum :)

**Comment by CallumVass** [comment]
Hi @xenatisch 

I am going to close this issue as I have created a PR where I have started the documentation process here: https://github.com/publichealthengland/coronavirus-dashboard-api-elixir-sdk/pull/1

Thanks for your swift help in getting the repo transferred and for all your help so far :)
