### ISSUE TITLE
Testing data by LTLA

### ISSUE THREAD

**Issue by radka-j** [publichealthengland/coronavirus-dashboard-api-python-sdk#9]
The number of tests (capacity, processed) seems to only be available at the national level. Is there a plan to start releasing test numbers by LTLA?

**Comment by xenatisch** [comment]
Hi @radka-j 

Thanks for getting in touch. I'm afraid this falls in the domain of our data team. My best recommendations is to get in touch via the email provided on the website and make a request. 

Sorry I couldn't be of more help.

**Comment by radka-j** [comment]
That makes sense, thank you for pointing me in the right direction!
